-- Materiais (vídeos) importados da pasta do Google Drive
-- Pasta: https://drive.google.com/drive/folders/1DfgtWpcHodGql7P_3fVZRX0C9b4s4K-J
-- Colar no Supabase > SQL Editor e executar. Roda como admin (ignora RLS).
-- created_at decrescente preserva a ordem da lista (Parte I antes de II, etc.).

insert into public.materials (title, description, category, level, video_url, created_at) values
  ('Arduíno', 'Introdução à placa Arduino: o que é, como funciona e para que serve nos projetos. Primeiros passos para programar e controlar componentes eletrônicos.', 'Eletrônica', 'Iniciante', 'https://drive.google.com/file/d/1p63atE8EFjEYAf2TmgVbzJGHWZ0AcauD/view', now() - interval '0 minutes'),
  ('Raspberry Pi', 'Apresentação do Raspberry Pi, o minicomputador usado nos projetos. Mostra suas principais funções e como ele dá mais autonomia aos brinquedos científicos.', 'Eletrônica', 'Intermediário', 'https://drive.google.com/file/d/1a4MBatTZQ8-GY-oV4BUcU4WhEyarB29m/view', now() - interval '1 minutes'),
  ('Impressão 3D', 'Como a impressão 3D é usada para criar peças e protótipos dos brinquedos. Acompanha o processo do modelo digital até a peça física impressa.', 'Impressão 3D', 'Intermediário', 'https://drive.google.com/file/d/1kOUH7lWOKschfsRdzca2yBPGWGCJwCHK/view', now() - interval '2 minutes'),
  ('Desenvolvimento de Produto - Parte I', 'Primeira etapa da criação de um produto: identificar o problema e levantar ideias. A base para transformar um conceito em um brinquedo científico.', 'Desenvolvimento de Produto', 'Iniciante', 'https://drive.google.com/file/d/1R-p8DgnWOMUSkffjcWjXxhWmNKkaOSgT/view', now() - interval '3 minutes'),
  ('Desenvolvimento de Produto - Parte II', 'Continuação do desenvolvimento, com foco em pesquisa e definição dos requisitos. Como organizar as ideias antes de partir para o protótipo.', 'Desenvolvimento de Produto', 'Iniciante', 'https://drive.google.com/file/d/1K4h7j72B63rhcAeGKmNpfrymzHaw8sSA/view', now() - interval '4 minutes'),
  ('Desenvolvimento de Produto - Parte III', 'Etapa de prototipagem: transformar o conceito em um primeiro modelo testável. Discute a escolha de materiais e a montagem inicial.', 'Desenvolvimento de Produto', 'Iniciante', 'https://drive.google.com/file/d/1h7jnTwepWB96aCriSsBqJiEc95mmukRM/view', now() - interval '5 minutes'),
  ('Desenvolvimento de Produto - Parte IV', 'Testes e ajustes do protótipo desenvolvido. Como avaliar o funcionamento e corrigir problemas antes da versão final.', 'Desenvolvimento de Produto', 'Iniciante', 'https://drive.google.com/file/d/1vCP1ppkks6D3VUmEXdbyWFj9n7rQ3oO2/view', now() - interval '6 minutes'),
  ('Desenvolvimento de Produto - Parte V', 'Finalização do produto e preparação para uso. Conclui o ciclo de desenvolvimento, da ideia ao brinquedo pronto.', 'Desenvolvimento de Produto', 'Iniciante', 'https://drive.google.com/file/d/1OezZr4FkUxv8sZXIGTkbHGlEehxpMa0M/view', now() - interval '7 minutes'),
  ('Oficina de Design - Parte I', 'Introdução à oficina de design: princípios de forma e estética aplicados aos projetos. Conceitos básicos para criar produtos atraentes e funcionais.', 'Oficina de Design', 'Iniciante', 'https://drive.google.com/file/d/11tD2O3kkj5M_uZr-7wUoTDl6sfaJMWKu/view', now() - interval '8 minutes'),
  ('Oficina de Design - Parte II', 'Continuação da oficina, explorando cor, layout e composição. Como aplicar esses elementos no desenvolvimento dos brinquedos.', 'Oficina de Design', 'Iniciante', 'https://drive.google.com/file/d/17T7GXTZzYibtXnnG-9jf9O5HZ094fA7s/view', now() - interval '9 minutes'),
  ('Oficina de Design - Parte III', 'Aprofundamento nas técnicas de design, com foco na experiência de quem usa. Ensina a pensar no público ao criar cada projeto.', 'Oficina de Design', 'Iniciante', 'https://drive.google.com/file/d/1J9C4MM5Zo6-ZiP4JHfuRTIjj8q65RW-f/view', now() - interval '10 minutes'),
  ('Oficina de Design - Parte IV', 'Aplicação prática dos conceitos de design em um projeto real. Demonstra o passo a passo, da ideia ao esboço final.', 'Oficina de Design', 'Iniciante', 'https://drive.google.com/file/d/1MTVaHxnjoM2i-yNq04shpbzy_bbDJhbO/view', now() - interval '11 minutes'),
  ('Oficina de Design - Parte V', 'Encerramento da oficina, revisando e refinando o resultado. Consolida tudo que foi aprendido nas etapas anteriores.', 'Oficina de Design', 'Iniciante', 'https://drive.google.com/file/d/1T0pJ2fzbBHLjfcvS6G67b0X3H_JzAjB-/view', now() - interval '12 minutes');

-- ── Adicionado depois: vídeo avulso "Disco de Newton" (rodar separado do bloco acima) ──
insert into public.materials (title, description, category, level, video_url, created_at) values
  ('Como montar o Disco de Newton', 'Passo a passo para montar um Disco de Newton e ver as cores se combinarem em branco ao girar. Mostra, na prática, como a luz branca é formada pela soma das cores.', 'Montagem', 'Iniciante', 'https://drive.google.com/file/d/1jCw2L-zmbDGsjKE7EU_j8lKX4UZNGty0/view', now());
